# Generated by Django 5.2.8 on 2025-11-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uom',
            field=models.CharField(default='Units', help_text='Unit of Measure (e.g., kg, pcs, dozen, liters)', max_length=50),
        ),
    ]
