# Generated by Django 5.2.8 on 2025-11-22 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_uom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action_type', models.CharField(choices=[('stock_move', 'Stock Move'), ('status_change', 'Status Change'), ('adjustment', 'Adjustment')], max_length=20)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('old_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('destination_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_move_history', to='inventory.location')),
                ('picking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_history', to='inventory.picking')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_history', to='inventory.product')),
                ('source_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_move_history', to='inventory.location')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='move_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Move History',
                'verbose_name_plural': 'Move History',
                'db_table': 'move_history',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='move_histor_timesta_029422_idx'), models.Index(fields=['product'], name='move_histor_product_2d6490_idx'), models.Index(fields=['picking'], name='move_histor_picking_3031f8_idx')],
            },
        ),
    ]
