# Generated by Django 5.2.8 on 2025-11-22 09:17

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_initial_settings(apps, schema_editor):
    """Create initial warehouse settings record."""
    WarehouseSettings = apps.get_model('inventory', 'WarehouseSettings')
    if not WarehouseSettings.objects.exists():
        WarehouseSettings.objects.create(
            low_stock_threshold=10
        )


def reverse_initial_settings(apps, schema_editor):
    """Remove initial warehouse settings record."""
    WarehouseSettings = apps.get_model('inventory', 'WarehouseSettings')
    WarehouseSettings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_movehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_threshold', models.IntegerField(default=10, help_text='Threshold for low stock alerts', validators=[django.core.validators.MinValueValidator(0)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_adjustment_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjustment_settings', to='inventory.location')),
                ('default_delivery_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_settings', to='inventory.location')),
                ('default_receipt_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_settings', to='inventory.location')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Warehouse Settings',
                'verbose_name_plural': 'Warehouse Settings',
                'db_table': 'warehouse_settings',
            },
        ),
        migrations.RunPython(create_initial_settings, reverse_initial_settings),
    ]
