# Generated by Django 4.2.26 on 2025-11-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_warehousesettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picking',
            name='reference',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
    ]
